### ISSUE TITLE
ytPlayer: PauseVideo event doesn't handle player icon change

### ISSUE THREAD

**Issue by ziyaddin** [headsetapp/headset-electron#10]
When user stops the video player, the player icon of the Headset player doesn't change.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1016523/26099364/8435365c-3a3b-11e7-9be3-d751db7134a1.png)

I think it is related with this part:

![image](https://cloud.githubusercontent.com/assets/1016523/26099647/6cd05d4c-3a3c-11e7-844b-4ce6a079b802.png)

**Comment by danielravina** [comment]
Yes I'm totally aware of that. This is currently a one-way communication. The main window is the master and the player is the slave. Events that are triggered by the player (except `ready`) do not affect the main window. Making it communicate two-way is a bit tricky due to Redux's workflow. I hoped it will be overlooked since users are not _supposed to_ (I know there's no such thing is software 😂) use the player to control the videos. Unfortunately, YouTube doesn't allow to hide or disable any of the controls on the player so we ended up in this situation. It's not that of a big deal IMO, and I'll find a solution once I have some free time. Thanks for pointing that out nonetheless!

**Comment by danielravina** [comment]
Finally, Issue is fixed!

**Comment by danielravina** [comment]
This fix is causing a bug that prevents tracks from playing in sequence because the state of the player is stuck in `PAUSED`. re-opening. will investigate further.

**Comment by fcastilloec** [comment]
The buttons states are still not synced.
On top of that. If you pause the video player, after a little less than 10 seconds the next track starts playing automatically. This might be related to "...the state of the player is stuck in PAUSED..."

**Comment by danielravina** [comment]
I reverted the change since it was causing issues - specifically, tracks are paused automatically after skip.

The 10 seconds is actually a fix for #6. There is no indication from the player on whether or not a video is available so there is a timer that periodically checks that a video is playing (i.e current time has changed) and the state is on `playing`. it's a bit of a hack but it works in most cases.
