### ISSUE TITLE
Open-sourcing the app?

### ISSUE THREAD

**Issue by m1guelpf** [headsetapp/headset-electron#13]
Hi!
Are there any plans on open-sourcing the app code?
I mean, with electron, you're just loading a private github repo, that contains the player & UI. Are there any plans on open-sourcing that?

**Comment by danielravina** [comment]
The short answer is no.
The long answer is that I treat this app as a business, and I plan to monetize it at some point in the future. I can't think of a way this could happen if I open source it as anyone will be able to bypass anything if they want. I decided to open source the wrappers so users could build it to any OS and because I can host the binaries on github easily. Sorry if this is not the answer that you were looking for, I hope It doesn't make me look like a greedy 🐷.

**Comment by m1guelpf** [comment]
@danielravina I totally understand, I recently did something like that with one of my projects :smile:
