### ISSUE TITLE
Pausing player-window will play next song after 10 seconds

### ISSUE THREAD

**Issue by chevi** [headsetapp/headset-electron#153]
### Description
Run playing some video
Click on video to pause it

### Expected behaviour
Video is still paused

### Actual behaviour
after 10 seconds next video will be played

### Your Environment

- What OS are you using?
Ubuntu 16.04
- What version of Headset? (copy and paste from the user profile page if possible)
core 1.8.2 Wrapper 1.8.1

**Comment by danielravina** [comment]
Hi thanks for reporting. This is one of those features that became a bug. this is done to "auto-skip" videos that are not available. the embedded player has no way to indicate that so the workaround is to wait a bit and if you are on a "play" state and time is not changing, the video is probably not available..

It becomes a bug when users want to pause the video through the player which I admit happens to me all the time. 

I think a way to fix it is instead of auto skipping, the app window will show a message _"Video is Paused or Unavailable"_ and will let the user to decide if they want to skip.

**Comment by fcastilloec** [comment]
This issues is fixed in #198
