### ISSUE TITLE
Unexpected behavior when using mouse wheel button

### ISSUE THREAD

**Issue by moyaldror** [headsetapp/headset-electron#163]
Hi, First I must say - I love this app :)

The issues I encountered are all related to the use of the wheel button.

1. When using the wheel button on any submenu under the `Radio` menu will cause a new window to get opened (with the correct content - for example clicking on  **/r/dubstep** will open  **/r/dubstep**) with double the size of the player where the left side is the player and the right side is just blank white.

2. When in a **Reddit** `Radio` station there is a link to the **Reddit** page under the song progress bar.
Using the wheel button on the link will open a new window (as described above) with the `Search` menu (as seen in the attached pic)

I'm using Windows 7, with Headset version 1.9.0

![image](https://user-images.githubusercontent.com/15344912/40471360-23eee444-5f3f-11e8-85b7-f0d6594ed415.png)

**Comment by fcastilloec** [comment]
I can confirm this bug, and it affects all OSs

**Comment by danielravina** [comment]
Thanks for reporting! The bug is fixed in core 2.0.7 (reopen the app and it won't happen again)

@moyaldror quick question - Are you typically using the middle mouse button to click on things? The fix I added was to disable the middle button altogether. There is a way thought to route the middle click to the left mouse click but I'm not sure if that's the intuitive way to do it.

I'm a mac user with a trackpad and a magic mouse so I wasn't even aware this is an issue :)

**Comment by moyaldror** [comment]
@danielravina  Hi, thanks for the quick fix!
And regarding your question - yes I use the middle mouse button a lot!
Every time I see a link - this is my weapon of choice :)

I think that disabling it is a good enough solution as using left click will open a new window (which is what i intended to do in the first place).
