### ISSUE TITLE
Headset 2.0.0 Stuck at Loading

### ISSUE THREAD

**Issue by SDVII** [headsetapp/headset-electron#180]
### Description

Every time I try to launch the app recently, it's stuck at the loading screen. I tired restarting it and reinstalling it, but to no avail.

### Expected behavior

The app would load.

### Actual behaviour

The app is stuck at the loading screen.

### Environment

- Windows 10 Home 64 bit
- Headset 2.0.0

### Screenshot

![screenshot_1](https://user-images.githubusercontent.com/10416702/41961400-0e6d94d6-79fb-11e8-8432-e08b71e1aa78.png)

**Comment by fcastilloec** [comment]
I tried to reproduce this but out of 20+ times, it happened only twice. I believe this might be due to network connection and not an error from our side.
You can also try deleting the configuration files, this might help to reload the app without having to reinstall. On Windows, you'll have to delete the folder `C:\Users\{yourUserName}\AppData\Roaming\Headset`. Do this while Headset is close and then start it again. Let me know how it goes.

PS: You might not be able to see the `AppData` directory at first, so make sure you can see all hidden and protected folders.

**Comment by fcastilloec** [comment]
@SDVII There was another issuer reported that might have been affecting you (#181). Can you reload the app and see if that might have fixed your issue?

**Comment by SDVII** [comment]
@fcastilloec Thanks for the reply, and sorry about the late response.

I am afraid that deleting the folder didn't change anything, and the only way I managed to run it again was to reinstall the application.

The issue is that this occurs often and randomly enough for it to be a bit of an inconvenience (it would've been OK if it's only after updates or something).

With that being said, I really love this app. Keep up the good work.
