### ISSUE TITLE
Mobile App?

### ISSUE THREAD

**Issue by CKGrafico** [headsetapp/headset-electron#21]
Are you planning to port this to Cordova or something?
Could I help?

**Comment by danielravina** [comment]
The app (private repo) is coupled with electron because of the integration between the two windows. It is relying on `ipcRenderer` to be available so it could distribute events to the embedded player. Cordova wouldn't support it so raw porting wouldn't be an option. The embedded player will have to be somehow integrated into the UI. From past experience, embedded players didn't work very well in iOS. (if you play something on a website, it will automatically go fullscreen). Not sure how it behaves on Android. 
I want to try React native. https://github.com/just-team/react-native-youtube-player looks promising!!
