### ISSUE TITLE
'tiny' isn't a valid option

### ISSUE THREAD

**Issue by Skayo** [headsetapp/headset-electron#228]
According to my knowledge, and the YouTube Player API Docs, there isn't an option `tiny` for `suggestedQuality`. There's only a `small`. 

Correct me if I'm wrong tho.

[- Link to the line in the code I'm talking about -](https://github.com/headsetapp/headset-electron/blob/fdfb2b8bd46fd42570c81475a00758bde608f673/shared/player/ytPlayer.js#L52)

**Comment by fcastilloec** [comment]
The API Docs don't show all possible element values, mainly because not every platform supports all of them.
If you ran `getAvailableQualityLevels()` you'll get the list of all possible ones, and `tiny` is one of them. For example, I think that iOS doesn't support `tiny` and that's why it might not be listed.
