### ISSUE TITLE
App not working in Ubunu under root account

### ISSUE THREAD

**Issue by farobarcha** [headsetapp/headset-electron#267]
### Description

App does not working in Ubuntu 16.04 root whereas it works fine when I logged in as a normal user or guest account.

### Expected behaviour

App should launch.

### Actual behaviour
This looks to be specific to electron. I have checked the logs and found this.
"Running as root without --no-sandbox is not supported. See https://crbug.com/638180."

### Your Environment

Ubuntu 16.04

### Screenshots

🖼

**Comment by fcastilloec** [comment]
I never thought anybody will run this app as root, it's usually discouraged to run an electron app as root because they are basically web browser that now has unchecked access to the whole machine.
Anyway, as you mentioned during your search, try running `headset --no-sandbox` as root and it will run, I tested it on my machine and it works.

**Comment by farobarcha** [comment]
Yeah, `headset --no-sandbox` worked the trick.
