### ISSUE TITLE
Linux window manager integration (command line)

### ISSUE THREAD

**Issue by fubarhouse** [headsetapp/headset-electron#292]
### Description

More of a question or a feature request - is there any way to grab information about what is playing or to use the controls for stop/pause/start/play/next/previous from a terminal?

### Expected behaviour

Just want to be able to get information via the command line, it's the only thing that would prevent me using this regularly.

### Actual behaviour

Cannot find any information or any way to achieve this.

### Your Environment

- What OS are you using?
  Arch Linux w/ bspwm
- What version of Headset?
  Latest HEAD (9fe91759f1993f0704470251457b326ac6c0aaed)

### Screenshots

n/a

**Comment by fcastilloec** [comment]
It was more of a question than a feature because you can already do this. :smile: 
Headset has MPRIS integration, which means you can control it and get information from any MPRIS app. This goes for any other app that works with MPRIS.
As mentioned, you can use any MPRIS software/app of your choosing but because you want the info on the command line, I suggest you use [playerctl](https://github.com/altdesktop/playerctl) which I use as my main way of controlling any players with custom shortcuts, not just the command line.

So, for example, while Headset is running (no need to start it from the command line), open a terminal and you can use the following commands:
```bash
playerctl -p headset play-pause            // play or pause Headset
playerctl -p headset volume 0.25           // adjust the volume to 25%
playerctl -p headset metadata 'xesam:url'  // Get the current playing song url
playerctl -p headset position 30+          // Fast Forward 30 sec
```
Just check their `--help` page for all the commands you can use. FYI, you can't use the `open` command since Headset doesn't implement it, all other ones work.

**Comment by fubarhouse** [comment]
Love it, thank you!!
