### ISSUE TITLE
App gives "Error: Invalid key" for any API key

### ISSUE THREAD

**Issue by kelmouloudi** [headsetapp/headset-electron#345]
Hi,

The 1st time I set up the app it worked as intended, I listened to and liked like 30 songs. But after I closed the app and opened it again, it asked for the API a second time. I pasted the same API key as the 1st time but it gave me the error "**Error: Invalid key**". The detail says **error 403: The request cannot be completed because you have exceeded your quota** :

![error](https://i.imgur.com/4bTBXFy.png)

Also, after signing-in, my "liked" page is blank (white), and every radio tells me "not available".

I made a second API but it gives me the same error. On my API page, it says "This key is unrestricted".

The first time, I installed Headset using the Deb file from the official website. After the error, I removed it and then reinstalled it using the software installer built in my Zorin OS system (same Headset version), but still the problem persists.

I'm using **Zorin OS 15** (based on **Ubuntu 18.04. 2 LTS**, uses GNOME 3.30. 2). Headset version: **Core: v2.11.0, Wrapper: v3.3.0**.

Thank you.

**Comment by danielravina** [comment]
Hi there,

It looks like the issue is with the key. Did you configure it to access the
YouTube API after creating the second one?

**Comment by kelmouloudi** [comment]
When I go to "YouTube Analytics API" under my project, it says "API enabled" with a "Manage" button. When I click it and go to Credentials, I see my 2 keys. But from here I can only rename them. Here are the options for each key: 

Application restrictions: None
API restrictions: Don't restrict key

**Comment by fcastilloec** [comment]
The problem is probably not with the YouTube access but rather that you've exceeded the limits. This has happened to me a couple of times while debugging errors, but having a second key (associated with a different email) solves it for me.
I believe the quota is per user account, not per key, so creating a second one will not solve the issue, unless it's from a different Gmail address.

You can check a detail graph of your quota by going here:

https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=YOUR_PROJECT_NAME

**Comment by kelmouloudi** [comment]
I created a new project and generated a new key for it, and this time it worked. However, I feel like I didn't really use the app long enough to exceed the quota, I only liked around 30 songs without listening to them fully and that's it.

**Comment by fcastilloec** [comment]
Google made some changes a while ago regarding their quota. It used to be a lot less, and that's why we were able to use a single key for all Headset users (we did have to ask Google to increase our limit significantly). With the changes, and Google not increasing our limits, we had to make the change to a per-user key.
You can probably ask for a quota increase, but there's no guarantee that they'll give you one. Sorry we can't do anything else to help

**Comment by kelmouloudi** [comment]
Thank you guys, the app is wonderful by the way.
