### ISSUE TITLE
Error: Command failed: 4294967295

### ISSUE THREAD

**Issue by jamesta696** [headsetapp/headset-electron#395]
### Description

Downloaded the latest version from the GitHub repository page and not able to run the application due to fatal error.

### Expected behaviour

When opening the application, it should open and able to play music.

### Actual behavior

**When trying to run the application, I'm presented with an error screen and not able to use the program. See screenshot below:**
![image](https://user-images.githubusercontent.com/14171094/126250725-9bb1dbc1-1ecf-4dde-807a-efb73c44342a.png)

### Your Environment

- What OS are you using?
**Windows 10 Home x64 21H1**

- What version of Headset? 
**Version 3.3.3**

Can someone help provide a fix for this issue?
Thanks!

**Comment by fcastilloec** [comment]
I've never seen this before. I'll try to see if I can reproduce it but it's going to take me some time since I'm quite busy with my day job these days.

**Comment by jamesta696** [comment]
> I've never seen this before. I'll try to see if I can reproduce it but it's going to take me some time since I'm quite busy with my day job these days.

Hi, thanks for the prompt response!
I totally understand, the error somehow disappeared but does happen from time to time while playing music, but doesn't crash the application if I "X" out the error.

So far working without that error today. I appreciate your time looking into that, even with our busy lives.

Thanks

**Comment by fcastilloec** [comment]
@jamesta696 I haven't been able to reproduce this issue in multiple Windows machines. I looked into the error messages, it seems it was related to Amazon AWS. I don't think it's an issue with Headset, it probably was some hiccup with Amazon servers since we use those for login information.
Have you experienced this issue again since then? I'm sorry I have no better answer

**Comment by Austint30** [comment]
I believe I am also having the same problem, but my error message looks slightly different. For me it happens every time I leave my computer for a while (I think after it wakes from sleeping the error appears). However, if I close the dialog the app continues as normal.
![image](https://user-images.githubusercontent.com/16272815/130005058-4cb35872-47e9-4827-8c98-33337ed1fb5a.png)

**Comment by fcastilloec** [comment]
@Austint30 thanks for the screenshot. Your error is more related to DNS than the original one. It could all be the same error showing symptoms in different ways.
I still haven't been able to reproduce this, it all seems to be a problem with `Squirell.Windows` which is what's used to package the app into an installer.
I'm going to spend some time this coming weekend to try to debug this and hopefully fix it.
As @Austint30 mentioned, this error shouldn't get in the way of using Headset, it usually only happens when trying to search for updates.

**Comment by fcastilloec** [comment]
I've done more digging on this issue. Both times the error appeared, it was related to `update.electronjs.org` and `amazonaws.com`.
I've looked at other applications that also had this error, it seems that the majority of these problems happen when running the app behind a proxy, in particular an authenticated proxy.

In any way, I think I came up with a workaround so our users don't have to see the error dialog if anything weird happens (i.e. no network connection, using a proxy, problem with Github server -or Amazon AWS which I think Github uses-, etc.), the update will attempt the next time and Headset should work without any issues.
