### ISSUE TITLE
Headset APT repository

### ISSUE THREAD

**Issue by m1guelpf** [headsetapp/headset-electron#43]
**Edit**: See [@fcastilloec's comment below](https://github.com/headsetapp/headset-electron/issues/43#issuecomment-320054442).

<details>
<summary>Original Post</summary>
Hi!
I've created an apt repository for Headset.

It works this way:

1. Linux user add the repository running `curl -s https://packagecloud.io/install/repositories/headsetapp/headset/script.deb.sh | sudo bash`
2. Linux user installs headset by typing `sudo apt-get install headset`
3. Every time a new update is available, users can simply `sudo apt-get upgrade` and headset will update.

This is much simpler, as users run the upgrade command on a dialy base, and headset will be auto-updated.

For this to work, I need to upload the .deb files, or I can give you upload access, what do you prefer?
</details>

**Comment by danielravina** [comment]
amazing. Thank you so much for doing it! I will update instructions on the website. I don't mind if you give me upload access.

**Comment by fcastilloec** [comment]
I'm not sure who's building the linux .deb packages for this new repo. Could you guys check issue #46 which is very easy to solve when creating the package.

**Comment by m1guelpf** [comment]
👍 for mirroring on launchpad

**Comment by fcastilloec** [comment]
After looking at Launchpad, it seems that electron apps won't work well there. Mainly because you can't fetch all of the electron modules needed while creating the package.

I was reading about PPA and repositories and came across this: [Publish your repository in 2 minutes](https://askubuntu.com/a/493577/6211). The answer was posted on 2014 but edited on April 2017, so it might still work. I think it's a better way to host the repository directly on GitHub as described on the link.

@m1guelpf repository is great, but because it's hosted on a third party site, it might not always be reliable and it's also hosted under @m1guelpf name, so some users might not trust that.

I'm going to try to set the repository on my fork and see if I don't get any errors (especially regarding GPG keys) we can move forward from there.

**Comment by m1guelpf** [comment]
@fcastilloec Maybe we could use the guide to host it in GitHub Pages?

**Comment by fcastilloec** [comment]
@m1guelpf I've created a branch called `repo` on my fork. It's almost working but I'm having trouble with the signatures on the Release file. The repository is on the `deb-packages` folder.
Feel free to test it on your own fork using your own GPG key.

Once this is working, the repository could even be hosted on the headset.co website itself. Nonetheless, @danielravina will have to sign the packages himself or delegate somebody to take care of that.

**Comment by m1guelpf** [comment]
@fcastilloec Maybe we could automate that with Travis? About your fork, this days I can help much because I don't have access to a computer, but I'll try to take a look :smile:

**Comment by fcastilloec** [comment]
@m1guelpf I'm not familiar with Travis but I just gave it access to my repo to play with it.

I think my repository is working properly. At the moment it's being signed by my own GPG key.
So, if anybody can test this, that would be great. The repository is:
`deb http://raw.githubusercontent.com/fcastilloec/headset-electron/repo/debian deb-packages/`
Which can be added through the graphical tool in Ubuntu, or by running in the terminal the command:
`echo "deb http://raw.githubusercontent.com/fcastilloec/headset-electron/repo/debian deb-packages/" | sudo tee -a /etc/apt/sources.list`

You also need to add the public key to the keyring (my public GPG key), for that you can run the command: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E168CD84`
or you can look on any keyserver online (MIT, Ubuntu, etc.) and download my public key (Fingerprint E168CD84) and add it manually.

I would really appreciate it if anybody can confirm that this is working. To test, you can uninstall the headset app. Add the repository and key, run `sudo apt-get update` and then install Headset by running `sudo apt-get install headset`
Let me know if anybody gets any errors.

Eventually, this app could be added to the Ubuntu repository so it's easily available through the Software Center to be installed in any Ubuntu-based distro.

**Comment by m1guelpf** [comment]
@fcastilloec Looks fantastic! I'll try to test it when I get to a computer. One suggestion, is considered a better practice to create a new file in sources.list.d instead of adding text to sources.list

**Comment by m1guelpf** [comment]
@fcastilloec 
```
W: http://raw.githubusercontent.com/fcastilloec/headset-electron/repo/debian/deb-packages/Release.gpg: Signature by key 826E0C7FB4CD8865339D76247C9D9BF3E168CD84 uses weak digest algorithm (SHA1)
```

**Comment by fcastilloec** [comment]
@m1guelpf thanks for testing it!!! I'm glad that it's working. I forgot about that warning, I just update the digest algorithm to SHA512 so it's gone. If you update your system, the warning should be gone.

The only problem I'm having now is that running `yarn run build` a second time will create a deb package twice as big. If you run it a third time, it will double again. So I can easily be getting a ~120M deb file. I'm not sure why this is happening. Deleting the `node_modules` and `build` folders sometimes helps but not always. I'm not sure if this has something to do with switching between branches or if there's a cache not being clear somewhere, but it's driving me crazy. Anyway, this is an unrelated issue to creating the repository.

Now @danielravina will have to decide where to host the repository and which key to use to sign the files

**Comment by m1guelpf** [comment]
@fcastilloec If you create a script that can generate the deb file, then we can make Travis generate it, and push it back to the repo. If you want, I can do that, but first we need @danielravina's opinion and a PGP key we can move to Travis (maybe using Travis hidden vars). Also, I'd like to do this in other repos, so would you mind writing the process you followed to create the files in your branch?

**Comment by fcastilloec** [comment]
@m1guelpf I'm not familiar with Travis, so I will leave that to you. Regarding the PGP key, I don't think that the private key should be stored anywhere online, just for security purposes. I'm not sure how Travis hidden vars work, so maybe that could be secure enough, I just always feel uneasy having a private key somewhere online. Like you said, @danielravina is the one with the final word regarding all this.

For creating the repository files, on my fork, on the branch `repo`, check the file `debian/bin/set-repository`. That script contains all the necessary steps to create the required files. I think the commands are easy to follow, nonetheless, let me know if you have questions. Just in case, those commands assumed that you have a private key added to your keyring (which I've always had). You'll have to figure out how to use gpg on Travis for signing (a quick search showed only cyphering, not signing).
Once the files are created, you just have to get the `url` of your repository and set it in the system as `deb url folder/` (for some reason the last slash is required). The original guide suggests using `deb url/folder ./` but I had so many problems with that syntax

**Comment by danielravina** [comment]
I'd like to move to Travis. Better check with @bil-elmoussaoui I think he is working on a PR for that https://github.com/headsetapp/headset-electron/issues/15#issuecomment-318868101

**Comment by fcastilloec** [comment]
@danielravina from what I understood from @bil-elmoussaou comment, you have to setup Travis on this repository first, after that @bil-elmoussaou can work on a PR. Nonetheless, Travis is a different issue, somewhat related to this one, but not necessarily. I think that opening a new issue just for Travis integration might be better.
In the meantime, we already have a packagecloud repository and a temporary repository hosted on my fork, which can be easily replicated on the original github project (or even headsetapp.co website).

So, what I'm wondering is, should we wait until Travis is setup so @danielravina can decide how/where the repository be hosted and integrated? Or, should we setup the repository already and then integrate it with Travis once it's running.

Anyway, I'm not familiar with Travis but it seems that we can [integrate it to Launchpad](https://docs.travis-ci.com/user/deployment/launchpad/), host the repository on [GitHub Pages](https://docs.travis-ci.com/user/deployment/pages/) or simply run a [script](https://docs.travis-ci.com/user/deployment/script/), which can be the one I created on my `repo` branch to host the files on headsetapp.co
I also found out that there's a way to [deploy to packagecloud](https://docs.travis-ci.com/user/deployment/packagecloud/) and maybe @m1guelpf could test this since he already owns a packagecloud repository and he's familiar with Travis.

**Comment by m1guelpf** [comment]
@fcastilloec I think it'd be better to move to Launchpad

**Comment by fcastilloec** [comment]
@m1guelpf it seems that we can't build electron apps on launchpad (see this [askUbuntu post](https://askubuntu.com/questions/794953/electron-app-as-ppa) )
And we can't just upload deb files to launchpad. Launchpad only takes source code, nothing else.
I'm editing my previous post to delete the launchpad mention since this is not really an option for this project.
If we want a PPA we will have to create an installer that fetches the compiled (not the deb) files and installs them in the system. This is a whole different project by itself, hosted on launchpad.

**Comment by danielravina** [comment]
I set up Travis with the project https://travis-ci.org/headsetapp/headset-electron

**Comment by bil-elmoussaoui** [comment]
@fcastilloec Are you sure you can't upload deb files to launchpad? https://help.launchpad.net/Packaging/PPA/Uploading

**Comment by fcastilloec** [comment]
@bil-elmoussaoui I've seen that page, here's a quote from the link you posted:

> Note that Launchpad builds the packages onsite, and does not accept deb files. The correct command for creating the Debian package source is 'debuild -S'.

So again, we either host it in github (a subfolder on this repo), github pages (a new repository), or on headsetapp.co. There's also packagecloud but I have my doubts about that.
At the end @danielravina has the final say

**Comment by bil-elmoussaoui** [comment]
@fcastilloec We at Ramme use Travis to publish the deb files directly to the release tag https://github.com/terkelg/ramme/releases/tag/v3.2.3

**Comment by danielravina** [comment]
I'd like to use the release tag as it is consistent with Windows and Mac.

**Comment by fcastilloec** [comment]
The release tags on github are not the same as an APT repository. The whole point of APT is that once a new version is released (publish deb file and other required files), it will be installed automatically on the user system. Github release tags only publish it so the user has to manually download the new version of the app. Also, I thought @danielravina was already doing this for all versions of Headset

**Comment by danielravina** [comment]
yes that's how it's done currently but it's a manual process. it's better to use Travis in order to automate it.

**Comment by bil-elmoussaoui** [comment]
@fcastilloec Who uses Launchpad anyway? It's the worst tool ever invented. You can't even compile native applications correctly. You think you will be able to do so with semi-native/hybrid apps like Electron ones? :laughing: 
Having a way to download the latest deb file is the best thing the dev can do at the moment. Or just publish a snap/flatpak package instead which is much easier to update than using that shitty tool (sorry for that word, but it's a sad truth)

**Comment by fcastilloec** [comment]
@bil-elmoussaoui I agree, the only good thing about Launchpad is just the PPA repositories, nothing else.
That's why we're trying to host a APT repository somewhere else (either github or headsetapp.co)
I already have a Travis configuration working but only for building packages. I'm testing how to publish them to an APT repository with Travis.

**Comment by fcastilloec** [comment]
After a lot of playing with Travis, I can say that there's no way to set up an APT repository automatically with them (unless it's with [packagecloud.io](packagecloud.io)).
We have to manage it manually because we need to sign some files and this is not possible, this is similar to what @danielravina mentioned on PR #53 when trying to setup OSX on Travis. By using `packagecloud.io` we let them take care of the signing.
I think we should settle with using `packagecloud.io` but that repository should be setup and own by @danielravina , this will also make it possible for hosting packages for other distros, including `rpm` based distros.
Travis can be setup to published using labels into GitHub, which is going to be very helpful

**Comment by m1guelpf** [comment]
I'd suggest to create another repo, use it as an apt repo and push the binaries from Travis. I can take care of the code to push it, if you want.

**Comment by danielravina** [comment]
The open source (free) version of packagecloud only allows 250mb of storage. this will only support one build at a time. maybe we can use the headsetapp.co repo (https://github.com/headsetapp/headsetapp.github.io) WDYT?

**Comment by fcastilloec** [comment]
@danielravina I think that the free version is enough storage. You only need the space to host the `deb` packages and a couple of small files. The small files won't take more than a couple of kB, the `deb` package is ~36MB right now, so 250MB looks like enough. Actually, packagecloud might not even consider the small files as part of the storage since they automatically create those file for release.
You don't have to publish the source files or anything similar there, just the `deb`.

On Travis, under the `deploy` tag, you can specify `local-dir: build/installers` to be scan for installers, and `package_glob: *.deb` as the only extension to be uploaded.

**Comment by danielravina** [comment]
ok sounds good. let's try packagecloud. I will sign up.

**Comment by danielravina** [comment]
ok for Travis, the config is:
```
before_install:
  - gem install package_cloud

script:
  - package_cloud push user/repo/os/version /path/to/package.ext
```
there's also an API token environment variable that I need to add.

**Comment by fcastilloec** [comment]
I'm not familiar with ruby so I don't really understand what that's doing. Is `package_cloud` a program/script that helps you upload your package to packagecloud?
Travis uploads automatically if a build is successful. You just need to add the `deploy` tag on the `.travis.yml` file. You can see the tags you need on `.travis.yml` [here](https://docs.travis-ci.com/user/deployment/packagecloud/).

**Comment by m1guelpf** [comment]
@danielravina The problem with packagecloud is that you need to upload the deb for every linux version you want to support, and that would make the space disappear before even having one version uploaded (personal experience). I'd stick with pushing to another branch or the website repo.

**Comment by danielravina** [comment]
@fcastilloec `gem install` is the same as `npm install` for ruby. @m1guelpf good point. I did think about it and 250mb will allow 5 - 6 distros. Wouldn't that be enough?

**Comment by m1guelpf** [comment]
@danielravina The problem is that you have to upload the file for every version of the distro you want to support. If you want Ubuntu, for example, you have to upload one for 10.4 (LTS), 10.10 (the one most users are on), 11.4 (latest)... When I tried to upload headset, uploading a version for both Ubuntu LTS & Ubuntu 10.10 filled all the space available.

**Comment by fcastilloec** [comment]
@m1guelpf You could just upload one version, for example, Ubuntu 16.04. And on `headsetapp.io` give instructions to add the 16.04 repository for all version of ubuntu/elementaryOS/debian/LinuxMint. Travis is using 14.04 to test the build, so technically you could only upload that version, since other version haven't been tested.
Currently, the `deb` file will work with almost all version of any debian based OS. Right now, headset has only one dependency to work, `dbus`, so it will work on multiple version without having to add specific packages for each version, it also doesn't require a specific version of `dbus` which could make it non-compatible with older versions.


@danielravina I see that the instructions you have came from packagecloud site Documentation, those instructions are outdated, it's before Travis implemented native support for packagecloud. 
You can see packagecloud [blog post](https://blog.packagecloud.io/eng/2017/01/17/continuous-delivery-python-applications-using-travis-ci-packagecloud/) for how to integrate using Travis built-in `deploy` tag. You can also look at the documentation on [Travis site](https://docs.travis-ci.com/user/deployment/packagecloud/) which also describes the same info that it's in the blog post.3
By using the `deploy` tag, you can leave the `script` tag for just running tests/building, which is what it was meant for. If the build/test is successful, then the `deploy` tag will kick in.

**Comment by m1guelpf** [comment]
@fcastilloec The problem with that is that we still have to upload one file for each distro... anyway, if it works, I'm :+1: with Packagecloud.

**Comment by fcastilloec** [comment]
@m1guelpf are you saying that packagecloud forces you to upload a package for each distro? otherwise, it won't publish any package?
As an example, let's say we upload one package for Ubuntu 16.04 (Xenial). The repository would look something like: `deb packagecloudURL/headseatapp xenial` and you could add that repository to Ubuntu 17.10 (Artful) as is (without replacing `xenial` to `artful`). Any Debian-based OS will add that repository as is, with the `xenial` key included.
I know that packagecloud provides some weird scripts for "easy" installation. But what that script is doing is the same as the instructions I provided on [this comment](https://github.com/headsetapp/headset-electron/issues/43#issuecomment-320054442), which are just two lines of code for copy/paste on a terminal. The script also makes sure that the `xenial` string gets replaced to whatever your system is, so by putting direct instructions on the site instead of an "easy" script, everybody can add the repository as is to any system.

The only exception would be if we find bugs specific to an OS version, then we might need to publish a specific package just for that version fixing the issue.

Also, I've been thinking of adding code to the `deb` package that would automatically add the repository when installing it. That means, when somebody downloads from the `headsetapp.co` or github, the repository will also be added automatically. I'm not 100% sure this can be done right now with electron tools. Nonetheless, this is something for the future and it needs the repository up and running for it to work.

**Comment by danielravina** [comment]
opened a PR with the deploy script. Please review https://github.com/headsetapp/headset-electron/pull/54

**Comment by danielravina** [comment]
just received this email from packagecloud:
```
Hi,

Looks like you are getting close to your overage:

Bandwidth: 56.08% used

Visit https://packagecloud.io/usage to turn off these emails or view usage history.

Thanks,

The packagecloud crew
```

That's 3 downloads.

**Comment by danielravina** [comment]
I downloaded the package couple of more times from https://packagecloud.io/headsetapp/headset-electron/packages/ubuntu/trusty/Headset_1.6.0-1_amd64.deb now it's over the usage but I can still download. It doesn't say in their FAQ what happens when you go over the limit

**Comment by danielravina** [comment]
```
Your account has been disabled because it has exceeded the maximum allowed overage 
for your account. Please login and upgrade your plan or increase your maximum overage. 

Visit https://packagecloud.io/usage for more information. 

Thanks, 

The packagecloud crew 
```

Ok packagecloud is definitely not an option.

**Comment by fcastilloec** [comment]
Wow!!! I didn't know there was a bandwidth limitation. packagecloud has a better 'free' plan for open source projects. We just have to contact them. But I agree @danielravina, I think it'll be better to deploy to github pages and host our own repo. In the meantime, we should setup github releases.
I just have to figure out how to automate the signing of `deb` packages.

**Comment by danielravina** [comment]
WDYT about this solution? https://github.com/headsetapp/headset-electron/issues/15#issuecomment-302519087

**Comment by fcastilloec** [comment]
It looks ok to me, the page doesn't have a lot of information. The Terms of Services says they are in a "state of testing" so we won't know if it will be free always, or if they'll introduce bandwidth restrictions.
They do have some code on how to integrate with Travis.
I'm going to try to crack on how to host your own repo on GitHub pages. I think that by using Travis hidden variables we could upload a private key (encrypted) which can be used to sign the files and publish.
If this works, you can also use Travis to sign the OSX packages.

PS: As a side suggestion, have you thought of creating a Slack account for headset? Or an IRC channel or anything like that where it'll be easier to talk/chat. I vote Slack, but anything is better than comments on Github I think. WDYT?

**Comment by m1guelpf** [comment]
:+1: for slack

**Comment by danielravina** [comment]
Here's the invite link: https://join.slack.com/t/headsetapp/shared_invite/MjI2MDc1NjUwODA0LTE1MDI2NTEwNjgtZTlkNmFiYTBiOQ

**Comment by danielravina** [comment]
APT is now available in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.1
