### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by sicu** [headsetapp/headset-electron#45]
Would be great to have a choice between a light and dark themed player.
Very happy with the player, great work! :D #

**Comment by danielravina** [comment]
Some updates on the progress: The dark theme design is ready! I would merge it after #38 is fixed since if you're using it on multiple machines, it will be really annoying to switch between themes all the time. 
This is how it will look like:
![screen shot 2017-10-06 at 11 48 40 pm](https://user-images.githubusercontent.com/3150871/31368931-ace9c726-ad35-11e7-8805-19a410ef5126.png)

**Comment by danielravina** [comment]
Dark theme is available. Change it via the profile page
click on:
<img width="96" alt="screen shot 2017-10-30 at 11 45 55 pm" src="https://user-images.githubusercontent.com/3150871/32210723-81ba5618-bdcc-11e7-9a68-60702e140c5b.png">

**Comment by m1guelpf** [comment]
@danielravina How about auto-changing based on time?
