### ISSUE TITLE
Now Playing tab

### ISSUE THREAD

**Issue by masonc15** [headsetapp/headset-electron#66]
Hello,

I selected a Youtube channel to play on shuffle through Headset.  While listening, I went into the settings and now I cannot go back to see the song currently playing.  None of the four menu options on the bottom bring me to the current queue.  Is this something that needs to be added?

**Comment by danielravina** [comment]
What were you doing in the setting? If you log-out or connect to last.fm, the app will reload and if there's a song playing, it will keep playing (since the video is in a different window). This is, unfortunately, an annoying (but yet low impact) issue and I need to think how to solve it. Suggestions are welcomed. Thanks for reporting!

**Comment by masonc15** [comment]
I think I did connect to last.fm actually!  I did see the song still playing in the separate window but no way to control via the main window.  Thanks for responding and I'm glad you are aware of the issue.  After restarting the app, the controls reappeared like normal.

**Comment by danielravina** [comment]
Duplicate #58
