### ISSUE TITLE
Gnome3: Minimize to tray option

### ISSUE THREAD

**Issue by andreisusanu** [headsetapp/headset-electron#8]
It would be nice to have the option to close to tray (notification area).

![image](https://cloud.githubusercontent.com/assets/2534555/26094972/960334ea-3a24-11e7-995d-ba6c4179d9d5.png)

**Comment by danielravina** [comment]
Hi Mr. Robot!
The Mac build works very similar where you click on the `x` and but it doesn't close it, it just hides the windows. Electron has a Tray [icon module](https://github.com/electron/electron/blob/master/docs/api/tray.md). I remember trying to make it work the same in Ubuntu but it didn't work for some reason and due to time restrictions, I decided to release it without it. Please open a PR if you figure out a good workflow. Thanks!

**Comment by andreisusanu** [comment]
Hi Daniel!

Please check out this resource: https://github.com/hokein/electron-sample-apps/tree/master/tray

I just tested and it works great on my Ubuntu Gnome OS.

It would be nice to have tray support for Headset.
Thanks!

**Comment by danielravina** [comment]
just a question, what options would you like to see on the tray?

**Comment by m1guelpf** [comment]
@danielravina Would be cool to have the song title, and media control buttons

**Comment by bil-elmoussaoui** [comment]
@danielravina @m1guelpf Sorry to interrupt here but if you really wish to support GNOME and all the other linux desktops is by just supporting MPRIS which can then show the songs directly from the notification center on GNOME, and what's great about it is when you click on that if i say "music notification" the application will be maximized. So please do that instead of using a tray icon on Linux. They're dead like really dead. What's sad is that a lot of applications now puts the tray icons on and they have no options other than exit and show window;

**Comment by Martina-Neumayer** [comment]
Yeap.. The tray icon would be great to have also in Mint Mate ;)
Like is in the - for example - messenger for desktop app. Is also an electron wrapped one.

**Comment by danielravina** [comment]
Fixed and available in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.0-linux
