### ISSUE TITLE
Provide i386 binary

### ISSUE THREAD

**Issue by khurshid-alam** [headsetapp/headset-electron#9]
It would be nice if we could have i386 binaries as well.

**Comment by danielravina** [comment]
Follow the instructions in the readme and you can build it to your environment

**Comment by khurshid-alam** [comment]
@danielravina 
Why was this closed? I couldn't build on my machine. It was showing many errors. If it requires only providing` --arch= ia32` why don't you compile on your machine and upload it to the website?

**Comment by danielravina** [comment]
sorry, I wasn't aware you are stil having errors. my last comment was 2.5 months ago, i closed it due to lack of activity on this issue. planning on building it for multiple environments using travis.

**Comment by slaci18** [comment]
Hi! Is there any kind of progress with the i386 port?

**Comment by fcastilloec** [comment]
I'm not sure if we will provide pre-compiled 32bit installers, but you can easily build one yourself from the code (follow the instructions on the README)
Setting up Travis, our CI, to automatically deploy 32bit is a lot more complicated since they use 64bit by default. This brings me to the fact that a lot of Linux distros are "dropping" 32bit support. [Elementary OS](https://elementaryforums.com/index.php?threads/loki-32-bit-version.2050/#post-2811) doesn't have one, [Solus](https://solus-project.com/forums/viewtopic.php?t=360), [Arch Linux](https://itsfoss.com/arch-linux-32-bit/) and even [Ubuntu](https://itsfoss.com/ubuntu-drops-32-bit-desktop/) is killing 32bit images. Even Fedora is making it harder to get 32bit ISOs with their latest release.
So with all this, it seems that supporting and creating 32bit software might not be the best idea, especially since setting up and automatic way to compile and release will involve a lot of work.

If anybody decides to create their own installer and need any help, feel free to reach us on Slack where I'll be more than happy to help.


`*` All links are to articles about dropping 32bit support.
