### ISSUE TITLE
Make headset into one window

### ISSUE THREAD

**Issue by weahforsage** [headsetapp/headset-electron#91]
### Expected behaviour

Actually i have little enchancement or request.

### Head set in 1 window(tab)
Please make headset app in only 1 window without seperate audio from video. 
Just move second window to 1st main video player, instead of static thumbnail image. Hope you understand :+1: 

### Your Environment

Linux Mint 18.3
Core: 1.3.6 Wrapper: 1.6.1
### Screenshots

🖼

**Comment by fcastilloec** [comment]
This got me thinking. Maybe we could have both windows "merged" by having two tabs on a window. Tabs can be created with the package [`electron-tabs`](https://www.npmjs.com/package/electron-tabs). It would be even better to "pin" the player tab so it's smaller and out of the way if that's even possible.
Anyway, I think the current behavior is working great, this recommendation is just personal preference and might look worse, who knows...

**Comment by weahforsage** [comment]
Thats very annoying when i switch the tabs.

**Comment by sibeliusg** [comment]
I would prefer just one window with player and video. The video is open somewhere anyway, so why not in one window?

**Comment by danielravina** [comment]
Thank you for raising this issue. as @m1guelpf said, under YouTubes' ToS, the app cannot hide the video in any way shape or form. It needs to have min size of 200x200 and without any overlay or frame (Source: https://developers.google.com/youtube/terms/required-minimum-functionality).
With the current UI, replacing the thumbnail with the video and/or adding tabs within the app, will violate this term as users have the ability to hide the player (minimize). I see it as a core feature of headset and I wouldn't change it for now. 

There was an app called Streamus (a very popular chrome extension) that tried to turn YT into a music player and they got shutdown because of these violations. Please have a look at this [email exchange between the creator and Youtube](http://i.imgur.com/15gaOf6.png). I am very reluctant in doing anything that will remotely get to these stages. AFAIK, headset might still be in the red zone even now.

**Comment by danielravina** [comment]
closing for now as a `wontfix` until further notices.

**Comment by nathanfranke** [comment]
I would never do this because it's against the terms of service, but _hypothetically speaking_ you could use KDE's window rules to match Window class `headset` and window title `Headset - Player` with "Minimized: Force Yes" and "Skip taskbar: Force Yes"

XFCE: [this may help](https://askubuntu.com/questions/646346/xfce-hiding-an-application-from-the-taskbar)

KDE:
![image](https://user-images.githubusercontent.com/14253836/112776322-0058fc00-9005-11eb-818c-0289133903b1.png)
