### ISSUE TITLE
Update brew cask automatically

### ISSUE THREAD

**Issue by danielravina** [headsetapp/headset-electron#95]
### Description

Allow Travis CI to update a new macOs version to the brew cask repo. Similar to
https://github.com/caskroom/homebrew-cask/pull/39987

**Comment by fcastilloec** [comment]
I'm closing this because there's no good way to do this. When sumbiting the PR for a new version, brew cask will download the new installer to verify its sha256sum, and this can happen before the installer is actually published which will result in the PR erroing.
This is very likely to happen because the macOS build finishes before other OSs (linux takes the longest because it's building two installers), so the new release isn't published yet and nobody can download from a Draft release on Github
